export const moroccanCities = [
    "Agadir",
    "Ain Harrouda",
    "Ait Melloul",
    "Asilah",
    "Azemmour",
    "Ben Guerir",
    "Beni Ansar",
    "Beni Mellal",
    "Berkane",
    "Berrechid",
    "Bouarfa",
    "Boujniba",
    "Boulemane",
    "Bouznika",
    "Casablanca",
    "Chefchaouen",
    "Chichaoua",
    "Dakhla",
    "Demnate",
    "El Aioun Sidi Mellouk",
    "El Jadida",
    "Errachidia",
    "Essaouira",
    "Fès",
    "Fnideq",
    "Guelmim",
    "Guercif",
    "Imzouren",
    "Ifrane",
    "Jerada",
    "Kenitra",
    "Khemisset",
    "Khénifra",
    "Khouribga",
    "Ksar El Kebir",
    "Laayoune",
    "Larache",
    "Martil",
    "M’diq",
    "Marrakech",
    "Meknès",
    "Midelt",
    "Mohammedia",
    "Nador",
    "Ouarzazate",
    "Oued Zem",
    "Oujda",
    "Rabat",
    "Safi",
    "Salé",
    "Sefrou",
    "Settat",
    "Sidi Bennour",
    "Sidi Ifni",
    "Sidi Slimane",
    "Sidi Yahya El Gharb",
    "Skhirate",
    "Tan-Tan",
    "Tanger",
    "Taounate",
    "Taourirt",
    "Tarfaya",
    "Taroudant",
    "Tata",
    "Taza",
    "Témara",
    "Tetouan",
    "Tinghir",
    "Tiznit",
    "Youssoufia",
    "Zagora"
].sort();
